Added ACL facilities
RedisLabs/rediscloud-go-api pull request #116
Opened 2023-06-21 14:04 UTC by JohnSharpe

2023-06-21 14:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/rediscloud-go-api?pullRequest=116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/rediscloud-go-api?pullRequest=116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/rediscloud-go-api?pullRequest=116) it.</sub>

2023-06-22 13:32 UTC, trentrosenbaum approved these changes

2023-06-22 13:34 UTC, wjam commented on service/access_control_lists/users/model.go
> +	//Links  *string `json:"links,omitempty"` // TODO Unclear of type
It's probably better to not add the commented out code, especially as the `links` attribute is unlikely to be used.

2023-06-22 13:38 UTC, wjam commented on service/access_control_lists/users/service.go
> +	err := a.client.Post(ctx, "create user", "/acl/users", user, &task)
There's possibly the opportunity to reduce code by having a `PostForResourceId` function on the `HttpClient` which will perform the `Post` & `WaitForResourceId`, as it's such a common pattern within this code base.

2023-06-22 13:41 UTC, wjam requested changes

2023-06-22 13:41 UTC, wjam commented on service/cloud_accounts/model.go
> -const (
Why are these being removed?

2023-06-22 13:41 UTC, wjam commented on service/subscriptions/model.go
> -	SubscriptionStatusActive = "active"
These shouldn't be removed

2023-06-22 13:43 UTC, wjam commented on service/subscriptions/model.go
> -	SubscriptionStatusActive = "active"
Unless they aren't being used in the provider? Although it's already part of the public API...

2023-06-22 13:43 UTC, JohnSharpe commented on service/subscriptions/model.go
> -	SubscriptionStatusActive = "active"
GoLand was reporting them as unused within the project, happy to revert the change

2023-06-22 13:45 UTC, wjam commented on service/subscriptions/model.go
> -	SubscriptionStatusActive = "active"
The IDE is correct, but they're used downstream. The idea is to follow a similar pattern to AWS, to have the enum values defined within the SDK alongside the API.

2023-06-22 14:04 UTC, JohnSharpe commented on service/access_control_lists/users/service.go
> +	err := a.client.Post(ctx, "create user", "/acl/users", user, &task)
That's a neat idea, but it looks like it would take a bit of a refactor to do.
If I find time later I'll circle back to it

2023-06-22 14:05 UTC, merged